coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default: false
      Server:
        target: 70
        # Allow the coverage to drop by X% and posting a success status.
        threshold: 5
        paths: "src/server"
      UI:
        target: 70
        # Allow the coverage to drop by X% and posting a success status.
        threshold: 5
        paths: "src/app"
    patch: false
    changes: false

comment: false
