coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    # Learn more at https://codecov.io/docs#yaml_default_commit_status
    Toolshedr Server:
      target: 70
      # Allow the coverage to drop by X% and posting a success status.
      threshold: 5
      branches: null
      paths: "src/server"
    Toolshedr UI:
      target: 70
      # Allow the coverage to drop by X% and posting a success status.
      threshold: 5
      branches: null
      paths: "src/app"
    project:  default: false
    patch: false
    changes: false

comment:
  layout: "header, diff"
  require_changes: false
  branches: master
  behavior: once
  flags: null
  paths:
    - src
