coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    # Learn more at https://codecov.io/docs#yaml_default_commit_status
    project:
      default: false
      Toolshedr Server:
        target: 70
        # Allow the coverage to drop by X% and posting a success status.
        threshold: 5
        branches: null
        paths: "src/server"
      Toolshedr Server:
        target: 70
        # Allow the coverage to drop by X% and posting a success status.
        threshold: 5
        branches: null
        paths: "src/server"
    patch: false
    changes: false

comment:
  layout: "header, diff"
  require_changes: false
  branches: master
  behavior: once
  flags: null
  paths:
    - src